create table if not exists guilds (
  guild_id text primary key,
  created_at timestamptz not null default now()
);

create table if not exists guild_channels (
  guild_id text not null references guilds(guild_id) on delete cascade,
  channel_id text not null,
  primary key (guild_id, channel_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  guild_id text not null references guilds(guild_id) on delete cascade,
  channel_id text not null,
  author_id text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_guild_channel_created_idx
  on messages (guild_id, channel_id, created_at);

-- Deny all access by default. The bot uses the service_role/secret key, which
-- bypasses RLS entirely, so this doesn't affect the bot's own queries.
-- It exists purely to stop the anon/authenticated keys from reading or
-- writing these tables via the public REST API.
alter table guilds enable row level security;
alter table guild_channels enable row level security;
alter table messages enable row level security;